version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hn
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hn
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: hn@poire.dev
        PGADMIN_DEFAULT_PASSWORD: hn
      ports:
        - "5050:80"
