{
 "title": "HackerNews",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Top HN stories",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT id, by, score, title, url FROM stories\nWHERE $__timeFilter(time)\nORDER BY score DESC;"
    }
   ]
  },
  {
   "title": "Newest HN comments",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT comments.by, stories.title as story, comments.text FROM comments\nJOIN stories ON stories.id = comments.story\nWHERE $__timeFilter(comments.time)\nORDER BY comments.time DESC;"
    }
   ]
  },
  {
   "title": "Total Story Upvotes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(score) FROM stories\nWHERE $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Total Comments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM comments\nWHERE $__timeFilter(time);"
    }
   ]
  }
 ]
}